### ISSUE TITLE
charm took 10 minutes to bootstrap

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/charm-microceph#113]
microceph-charm in handling one of the event took 10 minutes to complete the bootstrapping process.

Here are the relevant logs:
```
unit-microceph-0: 07:07:56 INFO unit.microceph/0.juju-log identity-service:6: Entering guarded section: 'Bootstrapping'
unit-microceph-0: 07:07:58 INFO unit.microceph/0.juju-log identity-service:6: Microceph RGW enabled: True
unit-microceph-0: 07:08:00 INFO unit.microceph/0.juju-log identity-service:6: Updating RGW Cluster configs
unit-microceph-0: 07:17:58 INFO unit.microceph/0.juju-log identity-service:6: Setting active status
unit-microceph-0: 07:17:58 INFO unit.microceph/0.juju-log identity-service:6: Completed guarded section fully: 'Bootstrapping'
unit-microceph-0: 07:17:58 INFO juju.worker.uniter.operation ran "identity-service-relation-changed" hook (via hook dispatching script: dispatch)
```

Uploaded microceph charm and snap logs:
[microceph-0-charm-debug.log](https://github.com/user-attachments/files/16832200/microceph-0-charm-debug.log)
[journal-microceph-0-machine.log](https://github.com/user-attachments/files/16832256/journal-microceph-0-machine.log)

Sunbeam launchpad bug: https://bugs.launchpad.net/snap-openstack/+bug/2077442

microceph charm version: reef/beta r69
microceph snap version:   reef/beta r1124

**Comment by hemanthnakkina** [comment]
Could be related: https://github.com/canonical/charm-microceph/issues/96

**Comment by UtkarshBhatthere** [comment]
was that not already fixed by the `--skip-restart` flag ?

**Comment by hemanthnakkina** [comment]
> --skip-restart

I don't see the usage of this flag in charm-microceph.

**Comment by gboutry** [comment]
Is there any news about this? Just got a hook taking 16 minutes to enable RGW, with:
charm latest/edge     76
snap 19.2.0~git+snap4c28584134  1185   squid/edge

This is really hurting installation time in Sunbeam

**Comment by sabaini** [comment]
Would it be possible to get DEBUG level logs for charm-microceph?

**Comment by sabaini** [comment]
Also, would you be able to post steps to repro? TIA :-)

**Comment by gboutry** [comment]
[debug-log.log](https://github.com/user-attachments/files/17311884/debug-log.log)
This is a throwaway instance, passwords are non-consequential in this file.
