### ISSUE TITLE
Microceph's join token is choosing the wrong ip address

### ISSUE THREAD

**Issue by gboutry** [canonical/charm-microceph#81]
## Version
snap info: 18.2.0+snap71f71782c5
juju info: 47

## What happens (observed behaviour) ?
Launchpad bug: https://bugs.launchpad.net/snap-openstack/+bug/2065700

The jwt to join the microcluster gives a wrong address, and there's no way to ask for the right address: 

```
eyJuYW1lIjoibWljcm9jZXBoLzEiLCJzZWNyZXQiOiJkMzdjYTY2Y2RhM
2MwYjYwMzZjNWJhMDNlNzZlMGI0ZWM3YTM1ODRjMjkzYWM1NTljNDg1OGZiMGVhZTA2YWQ5IiwiZmluZ2VycHJpbnQiOiJkMGIxMmVmMzE3NjllY2ZmYjYzNTE0MWFkZjEzNDY5NDk0NmFhMGU1NzM3ODgyOTYyNGZmMjhjN2JhOWY1ZDc5Ii
wiam9pbl9hZGRyZXNzZXMiOlsiMTAuMS4zMi4xOTI6NzQ0MyJdfQ==
```
Address in jwt: 10.1.32.192:7443
This is a calico address only available on the bootstrap node. There's currently no way for the snap to chose the right address to create a jwt.

## More info
Joining will fail because the calico address chosen is not routable between nodes

**Comment by UtkarshBhatthere** [comment]
Hey @gboutry this should be resolved with the network spaces right ?

**Comment by gboutry** [comment]
It should, I'll re-open if it's not solved

**Comment by serafdev** [comment]
I'm also having this error, this `sudo microceph cluster add node-x` is using the external IP but I have multiple interfaces, my `cluster_network` is set to the internal one on which my nodes are connected

**Comment by UtkarshBhatthere** [comment]
@serafdev use `--microceph-ip` if you are using the snap directly.
